name: megaohm_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: '>=4.0.1 <5.0.0'
  google_fonts: ^3.0.1
  uuid: ^3.0.7
  connectivity_plus: ^3.0.2
  responsive_framework: ^0.2.0
  get: ^4.6.5
  getwidget: ^3.0.1
  flex_color_scheme: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.2.14
  device_info_plus: ^5.0.0
  intl_phone_field: ^3.1.0
  jwt_decoder: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/