import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'allClear': 'Clear',
          'code': 'Code',
          'EnterCode': 'Enter code (sent to email)',
          'confirm': 'CONFIRM',
          'validPhone': 'Enter a valid phone number please',
          'validName': 'Enter a valid name please',
          'validEmail': 'Enter a valid e-mail please',
          'yourName': 'Your name',
          'agreeToTheTerms': 'Agree to the terms of the user agreement please',
          'userAgreementTerms': 'User Agreement Terms',
          'iHaveReadAndAccept': 'I have read and accept ',
          'emptyField': 'Fill in the empty field(s) please',
          'language': 'English',
          'noInternet': 'Turn on the Internet please!',
          'invalidMobileNumber': 'Invalid Mobile Number',
          'didNotReceiveCode': 'Didn’t receive code?',
          'get': 'Get the code again',
          'PhoneNumber': 'Your phone Number',
          'enterСodeText':
              'Enter the last 4 digits of the number from which we will call you. For example:\n +1_123_456_XXXX ⬅',
          "pinIsIncorrect": "Incorrect code, please try again",
          'welcome': 'Welcome',
          'Email': 'Your email',
          'password': 'Your password',
          'enter': 'Enter',
          'registration': 'Registration',
          'doRegistration': 'REGISTER ONESELF',
          'toComeIn': 'INPUT',
          'profile': 'profile',
          'lightDarkModes': 'Light/Dark modes',
          'languages': 'Languages',
          'instruction': 'Instruction',
          'contactWithDevelopers': 'Contact with developers',
          'settings': 'Settings',
          'AppBarTitle': 'Megaohm',
        },
        'ru_RU': {
          'allClear': 'Понятно',
          'code': 'Код',
          'EnterCode': 'Введите код (отправлен на е-маил)',
          'confirm': '  ПОДТВЕРДИТЬ',
          'validPhone': 'Пожалуйста, введите корректный номер телефона',
          'validEmail': 'Пожалуйста, введите корректный e-mail',
          'validName': 'Пожалуйста, введите корректное имя',
          'yourName': 'Имя',
          'agreeToTheTerms': 'Пожалуйста, согласитесь с условиями пользовательского соглашения',
          'userAgreementTerms': 'Условия пользовательского соглашения',
          'iHaveReadAndAccept': 'Я ознакомлен(а) и принимаю ',
          'emptyField': 'Пожалуйста, заполните пустые поля',
          'language': 'Русский',
          'noInternet': 'Включите пожалуйста интернет!',
          'invalidMobileNumber': 'Некорректный номер телефона',
          'didNotReceiveCode': 'Не получили код?',
          'get': 'Получить код повторно',
          'welcome': 'Добро пожаловать!',
          'PhoneNumber': 'Номер телефона',
          'enterСodeText':
              'Введите последние 4 цифры номера с которого мы вам позвоним. Например:\n +7_123_456_XXXX ⬅',
          "pinIsIncorrect": "Некорректный код, попробуйте ещё раз.",
          'Email': 'Почта',
          'password': 'Ваш пароль',
          'enter': 'Вход',
          'registration': 'Регистрация',
          'doRegistration': 'ЗАРЕГИСТРИРОВАТЬСЯ',
          'toComeIn': 'ВОЙТИ',
          'profile': 'Профиль',
          'lightDarkModes': 'Ночной/Дневной режимы',
          'languages': 'Языки',
          'instruction': 'Инструкция',
          'contactWithDevelopers': 'Связь с разработчиками',
          'settings': 'Настройки',
          'AppBarTitle': 'Мегаом',
        }
      };
}
